spring:
  config:
    import: optional:env/env.properties
  mvc:
    servlet:
      path: /api/gamedataservice/

springdoc:
  swagger-ui:
    path: /api/docs/swagger-ui.html
  api-docs:
    path: /api/docs

riot:
  api:
    resttemplate:
      dev-mode: true
      rate-limits:
        contexts: App, Method

    latest-game-version: 13.7.1
    regions:
      euw:
        base-url: https://euw1.api.riotgames.com
        apis:
          summoners:
            url: ${riot.api.regions.euw.base-url}/lol/summoner/v4/summoners/
      europe:
        base-url: https://europe.api.riotgames.com
        apis:
          matches:
            url: ${riot.api.regions.europe.base-url}/lol/match/v5/matches/
    data-dragon:
      latest-version: 13.7.1
      base-url: https://ddragon.leagueoflegends.com/cdn/
      types:
        assets:
          extension: img
          subjects:
            profile-icons:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.latest-version}/${riot.api.data-dragon.types.assets.extension}/profileicon/
            runes:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.types.assets.extension}/
            summoner-spells:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.latest-version}/${riot.api.data-dragon.types.assets.extension}/spell/
            champions:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.latest-version}/${riot.api.data-dragon.types.assets.extension}/champion/
            items:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.latest-version}/${riot.api.data-dragon.types.assets.extension}/item/
        data:
          extension: data
          subjects:
            runes:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.latest-version}/${riot.api.data-dragon.types.data.extension}/en_US/runesReforged.json
            summoner-spells:
              url: ${riot.api.data-dragon.base-url}${riot.api.data-dragon.latest-version}/${riot.api.data-dragon.types.data.extension}/en_US/summoner.json
    key: ${RIOT_API_KEY}

server:
  port: 8082

jwt:
  key:
    secret: ${SECRET:#{null}}
    signature: BeqbvWM1mem/MP887bU919s3AAQmFl6cdanzq5h7LZof9Cz2XsQcAXGuqGziW6t0zAkoB6bevoj/JYN/4sIPjWKoibQr3YsigC4Fiip6CN0=

